# Site settings
title: Marc MacLeod
description: "Marc MacLeod, software engineer and designer. I'm a full stack developer creating iOS and web apps. I specialize in Node.js, Ruby, and Objective C."
baseurl: ""
url: "http://marbemac.com"
email: hi@marbemac.com
twitter_username: marbemac
github_username:  marbemac
linkedin_username:  marcmacleod

# Build settings
markdown: kramdown
permalink: pretty